### ISSUE TITLE
Facebook Links are adding non-working Suffix to URL

### ISSUE THREAD

**Issue by treyfour** [helloGov/webapp#244]
AS A: User
I WANT: To copy the campaign URL into a facebook post, and share link.
WHEN I: Copy the link into Facebook to share post, it adds a suffix (facebook tracking url) that makes it so the address search won't submit address to move to next screen.

E.G.
The long bit Facebook adds to the URL in a shared post is causing an issue with the address field being able to be submitted: 
https://www.hellogov.app/vgSZ-Yz-8?fbclid=IwAR1Au3hAH9uOxzb8_j6TuxIeTN5DJO6sJJsKAZRK5AdqmZEa9FCQWD1Ql8
Try an address on S Kenwood Ave Chicago IL.

If you delete the FB share junk it works fine: https://www.hellogov.app/vgSZ-Yz-8

**Comment by ahrGNUts** [comment]
@treyfour It looks like the problem is the way we're pulling the campaign ID from the URL. Our code currently doesn't parse out query string params, so it's trying to search for the campaign ID using the campaign ID, the ?, and everything that comes after it.

There are also a number of other places in the code where there are FIXME comments related to the way we're grabbing things from the URL. Workin on a fix now; if this works well here, we can probably apply it to the other places as well.

**Comment by ahrGNUts** [comment]
PR #249 is up now
