### ISSUE TITLE
Display completed signups below pending signups in superadmin view

### ISSUE THREAD

**Issue by kate-rose** [helloGov/webapp#257]
AS A super admin, username "admin" 
WHEN I look at hellogov.app/admin
I WANT TO see users who have completed their signups below the "Pending signups" display:

<img width="816" alt="Screen Shot 2019-06-10 at 8 35 42 PM" src="https://user-images.githubusercontent.com/19698792/59242324-f52ea500-8bbf-11e9-92b5-27c35e7d340d.png">

Please display invited email, First and Last Name, and accepted date in the 3 columns.

**Comment by ahrGNUts** [comment]
@kate-rose what do you think about more control over signed up users from the admin page? Like instead of just displaying information about them, should we have the ability to alter user data? 

Do we have a means of deleting users from the app other than deleting them from the database directly? 

Should we have a means of blocking logins for a certain account if we discover a user is using the app maliciously?

Should we track and display something like login data for users (or at the very least a timestamp for their most recent login)?

**Comment by kate-rose** [comment]
@ahrGNUts In addition to the original issue above, I think these are great ideas. I would definitely prioritize deletion first, blocking second, and then last login 3rd. 

Let's break them out in to another issue. Is it easier for you if they each have their own? Or multiple under an "add advanced admin controls" type issue?

**Comment by ahrGNUts** [comment]
@kate-rose I think I like rolling them into an "add advanced admin controls" issue. 

We might also want to have a link to the admin area for superuser sidebars:
![admin link](https://user-images.githubusercontent.com/5104274/60862024-358a3e80-a1d1-11e9-8d7d-f2db3c7722d1.png)
