### ISSUE TITLE
Add Campaign Field Length Feedback

### ISSUE THREAD

**Issue by patchneranartkomol** [helloGov/webapp#258]
Related to #58 and #254.

AS A: logged-in user
WHEN I: type over the character limit in the campaign fields
I WANT TO: receive visual feedback that I've typed over the limit. (See example from the Registration form)

Over Max Characters in Campaign Field
<img width="842" alt="Screen Shot 2019-06-10 at 8 40 34 PM" src="https://user-images.githubusercontent.com/8117210/59242381-2909ca80-8bc0-11e9-9034-fa39d51d7a93.png">

Registration Validation Feedback
<img width="718" alt="Screen Shot 2019-06-10 at 8 35 58 PM" src="https://user-images.githubusercontent.com/8117210/59242290-d16b5f00-8bbf-11e9-95c1-036f6d5bbe47.png">

**Comment by ahrGNUts** [comment]
Since those textareas won't let you type over the character limit (and therefore won't trigger an invalid form state like some other inputs will), maybe we can implement a dynamic character counter for those fields? Instead of 'Max 1000 characters' it could be '70/1000' or '930 characters remaining'
